//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATISWeb.MoneyWalletManagement {
    
    
    public partial class WfMoneyWallet {
        
        /// <summary>
        /// ScriptManager131 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.ScriptManager ScriptManager131;
        
        /// <summary>
        /// WCViewerNSSSoftwareUser control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ATISWeb.LoginManagement.WCViewerNSSSoftwareUser WCViewerNSSSoftwareUser;
        
        /// <summary>
        /// WCMoneyWalletCharging control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ATISWeb.MoneyWalletManagement.MoneyWalletChargingManagement.WCMoneyWalletCharging WCMoneyWalletCharging;
        
        /// <summary>
        /// WCMoneyWalletChargeRecordsCollectionInteligently control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ATISWeb.MoneyWalletManagement.WCMoneyWalletChargeRecordsCollectionInteligently WCMoneyWalletChargeRecordsCollectionInteligently;
        
        /// <summary>
        /// WCMoneyWalletAccouning control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ATISWeb.MoneyWalletManagement.WCMoneyWalletAccouning WCMoneyWalletAccouning;
    }
}
