//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATISWeb.TransportationAndLoadNotification.LoadCapacitorManagement {
    
    
    public partial class WfLoadCapacitorLoadManipulation {
        
        /// <summary>
        /// ScriptManager131 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.ScriptManager ScriptManager131;
        
        /// <summary>
        /// WCViewerNSSSoftwareUser control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ATISWeb.LoginManagement.WCViewerNSSSoftwareUser WCViewerNSSSoftwareUser;
        
        /// <summary>
        /// WcLoadCapacitorLoadManipulation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ATISWeb.TransportationAndLoadNotification.LoadCapacitorManagement.WcLoadCapacitorLoadManipulation WcLoadCapacitorLoadManipulation;
        
        /// <summary>
        /// WcLoadCapacitorLoadsCollectionIntelligently control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ATISWeb.TransportationAndLoadNotification.LoadCapacitorManagement.WcLoadCapacitorLoadsCollectionIntelligently WcLoadCapacitorLoadsCollectionIntelligently;
        
        /// <summary>
        /// WcLoadCapacitorLoadLoadPermissionsIssuedforToday control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ATISWeb.TransportationAndLoadNotification.LoadAllocationManagement.WcLoadCapacitorLoadLoadPermissionsIssued WcLoadCapacitorLoadLoadPermissionsIssuedforToday;
        
        /// <summary>
        /// WcLoadCapacitorLoadLoadPermissionsIssued control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ATISWeb.TransportationAndLoadNotification.LoadAllocationManagement.WcLoadCapacitorLoadLoadPermissionsIssued WcLoadCapacitorLoadLoadPermissionsIssued;
    }
}
