//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATISWeb.TransportationAndLoadNotification.LoadAllocationManagement {
    
    
    public partial class WcLoadCapacitorLoadLoadAllocationLoadPermissionIssue {
        
        /// <summary>
        /// BtnNewLoadAllocation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button BtnNewLoadAllocation;
        
        /// <summary>
        /// UpdatePanelWcViewerNSSLoadCapacitorLoad control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel UpdatePanelWcViewerNSSLoadCapacitorLoad;
        
        /// <summary>
        /// WcLoadCapacitorLoadsCollectionSummaryIntelligently control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ATISWeb.TransportationAndLoadNotification.LoadCapacitorManagement.WcLoadCapacitorLoadsCollectionSummaryIntelligently WcLoadCapacitorLoadsCollectionSummaryIntelligently;
        
        /// <summary>
        /// WcViewerNSSLoadCapacitorLoad control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ATISWeb.TransportationAndLoadNotification.LoadCapacitorManagement.WcViewerNSSLoadCapacitorLoad WcViewerNSSLoadCapacitorLoad;
        
        /// <summary>
        /// WcSmartCardsInquiry control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ATISWeb.TransportationAndLoadNotification.SmartCards.WcSmartCardsInquiry WcSmartCardsInquiry;
        
        /// <summary>
        /// PnlTurnStatus control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel PnlTurnStatus;
        
        /// <summary>
        /// LblTurnStatus control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label LblTurnStatus;
        
        /// <summary>
        /// BtnLoadAllocation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button BtnLoadAllocation;
    }
}
