//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATISWeb.TransportationAndLoadNotification.LoadAllocationManagement {
    
    
    public partial class WcLoadCapacitorLoadLoadPermissionsIssued {
        
        /// <summary>
        /// LblCaption control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label LblCaption;
        
        /// <summary>
        /// UpdatePanelWcLoadCapacitorLoadLoadPermissionsIssued control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel UpdatePanelWcLoadCapacitorLoadLoadPermissionsIssued;
        
        /// <summary>
        /// WcLoadCapacitorLoadsCollectionSummaryIntelligently control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ATISWeb.TransportationAndLoadNotification.LoadCapacitorManagement.WcLoadCapacitorLoadsCollectionSummaryIntelligently WcLoadCapacitorLoadsCollectionSummaryIntelligently;
        
        /// <summary>
        /// GridViewLoadCapacitorLoadLoadPermissionsIssued control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.GridView GridViewLoadCapacitorLoadLoadPermissionsIssued;
    }
}
